# 4.6 IC Combining and exporting data

# Table of Contents

#### 01. Import libraries

#### 02. Combining data

#### 03. Task 4.6

#### Step 2 - Export merged dataframe to pkl format

# 01. Import libraries

In [39]:
# Import libraries
import pandas as pd
import numpy as np
import os

# 02. Combining data

In [43]:
# Import dataframe
path = r'C:\Users\dirk8\CareerFoundry Projects\03-2025 Instacart Basket Analysis'
df_ords = pd.read_csv(os.path.join(path, 'Data', 'Prepared Data', 'orders_checked.csv'), index_col = False)

In [9]:
# Check the output
df_ords.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0

In [11]:
# Import another, new dataframe
df_ords_prior = pd.read_csv(os.path.join(path, 'Data', 'Original Data', 'EX 4.3', 'orders_products_prior.csv'), index_col = False)

In [15]:
# Check the output
df_ords_prior.head()

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [17]:
# Check dimensions
df_ords.shape

(3421083, 6)

In [19]:
df_ords_prior.shape

(32434489, 4)

In [45]:
# Merge the 2 dataframes using default "inner join" type by omitting a "how" argument
# Add "indicator = True" argument to add a merge flag column, to look at matches

df_merged_large = df_ords.merge(df_ords_prior, on = 'order_id', indicator = True)

In [23]:
# Check the output
df_merged_large.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge
0,2539329,1,1,2,8,NaN,196,1,0,both
1,2539329,1,1,2,8,NaN,14084,2,0,both
2,2539329,1,1,2,8,NaN,12427,3,0,both
3,2539329,1,1,2,8,NaN,26088,4,0,both
4,2539329,1,1,2,8,NaN,26405,5,0,both

In [47]:
# Check matches in the merge flag column values
df_merged_large['_merge'].value_counts()

_merge
both          32434489
left_only            0
right_only           0
Name: count, dtype: int64

# Caveat on the output merge flag values interpretation for joins that are not "how = 'outer'"

In [29]:
# Exercise 4.6 points out that the counts above only showed entries with a value of "both" from the default "inner join" merge
# But that does not tell us whether we have a full match
# To check for full match, we need to check the frequency of a merge flag column using a "how = 'outer'" argument, eg an "outer join" merge
# As per Exercise 4.6, doing so would show 32434489 count of "both" and a 206209 count of "left_only".  Thus, NOT a full match

In [33]:
# Check the output dimensions
df_merged_large.shape

(32434489, 10)

# 03. Task 4.6

# Step 2 - Export merged dataframe to pkl format

In [37]:
# Export merged dataframe to pkl format

df_merged_large.to_pickle(os.path.join(path, 'Data', 'Prepared Data', 'orders_products_combined.pkl'))